---
- name: Set AWS_PROFILE
  lineinfile: 
    path: "/etc/environment" 
    regexp: "^AWS_PROFILE="
    line: "AWS_PROFILE={{ aws_profile }}"

- name: Set OAR_SETTINGS_BUCKET
  lineinfile:
    path: "/etc/environment" 
    regexp: "^OAR_SETTINGS_BUCKET="
    line: "OAR_SETTINGS_BUCKET={{ oar_settings_bucket }}"
